baseURL = "https://www.takahito.com"
languageCode = "ja-jp"
title = "東本研究室"
theme = "soho"
enableInlineShortcodes = true

summarylength = 10
enableEmoji = true

[permalinks]
  post = "/:filename/"

[params]
author = "Takahito Tomoto"
description = "Takahito Tomoto's Laboratory"

copyright = "Takahito Tomoto"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

profilePicture = "android-chrome-512x512.png"
[menu]
[[menu.main]]
  name = "東本 崇仁"
  url = "/tomoto/"
  weight = 1
[[menu.main]]
    name = "研究内容"
    url = "/research/"
    weight = 2
  [[menu.main]]
    name = "構成員"
    url = "/members/"
    weight = 10
[[menu.main]]
    name = "研究業績"
    url = "/publications/"
    weight = 20
